### ISSUE TITLE
Weeks of June 13th & 20th - ToDos

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1011]
- [x] #942 - Post Author Order - K & S
- [x] #912 - Page Title for Promoting Content on Home Page - K & R
- [x] #439 #448 - Integrate Table and Button Streamfield Blocks - K
- [x] #990 - Allow Elements to break post body max width - K
- [x] #974 - iFrame Streamfield Block - K
- [ ] - Finalize Site Dataviz Structure/Create Data Projects Content Type - K
- [x] - Design/Groundwork for ISP Drone Strikes Rework - K
- [x] #963 EdCentral Transfer - S & R
- [ ] #1012 LisaG Request for Old Site Data - N
- [ ] #1014 In the News to Articles Database Transfer - S
- [ ] #1015 Simple Page Database Transfer - S
- [x] #1013 Pagination Duplication - S
- [x] #995 Test for Author Order - S
- [x] #1017 EdCentral WordPress Redirects - S
- [ ] #1016 Issues with Scheduling Post - S
- [x] #1019 - Improve Site-Wide Video IFrame Responsiveness - K
- [x] #1020 - Full Width Subscribe Boxes on Home Page/Program Landing Pages - K
- [x] #1024 - Subscribe Page - Spam Checks to Prevent Nonhuman Form Submission - K
- [ ] #976 - Prevent Uploading of File with Same Name - S
- [x] #879 - RSVP field not required - S
- [x] #550 - Author content under bio - S
- [x] #1038 - Rearrange Sidemenu Order - K
- [x] #925 - Automate Events Carousel on Home Page - K
