### ISSUE TITLE
Week of June 27th - ToDos

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1055]
- [x] #1048 - Formatting Changes to Program Blog Home Page - K
- [x] #1035 - Build out Subscriptions Page Model - K
- [ ] Finalize Site Dataviz Structure/Create Data Projects Content Type - K, R
- [ ] #300 - Bio Contact Buttons - K, R, S
- [x] #259 - Build Out Donate Page (now that we have button and iframe blocks) - Comms Team
- [x] - Care Index Project Meeting/Planning - K, R
- [ ] #976 - Prevent Uploading of File with Same Name - S
- [ ] #1016 Issues with Scheduling Post - S
- [x] #1014 In the News to Articles Database Transfer - S
- [ ] #1015 Simple Page Database Transfer - S
- [x] Dynamically Add Location Programs to Top Nav - K
- [x] #1061 EdCentral Redirects to Ed Subprogram/Initiative Pages - S
- [x] Add documentation to repo and update README - S
