### ISSUE TITLE
Week of July 4th - ToDos

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1071]
- [ ] #1037 - Build out Data Viz Project Structure - K
- [x] #300 - Bio Contact Buttons - B
- [ ] #925 - Resolve Circular Dependency Issue for Events Carousel - S, K
- [x] #1035 - Finish tests for new subscriptions setup - K
- [ ] #259 - Style Donate Embed - B, K
- [ ] #1072 - Investigate new Jobs Listing Service - G, R
- [ ] #1073 - Decide what New America HQ should be called/differentiate between DC and HQ - R
- [x] Knowledge Sync - Deployment, Remaining Database Structure, content migration, testing infrastructure, AWS - S, K
- [x] Fix Drones Primer Design - G
- [x] #976 - Prevent file upload with same file name - S
- [x] #1016 - Scheduling published pages - S
