### ISSUE TITLE
Week of July 11th - ToDos

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1077]
- [x] #1037 - Build out Data Viz Project Structure - K
- [ ] #259 - Style Donate Embed - B, Jacqueline, R
- [ ] #1073 - Decide what New America HQ should be called/differentiate between DC and HQ - R
- [ ] Designs for Social media sharing - R, B
- [x] Designs for In-Depth Projects Home Page - R
- [x] #925 - Resolve Circular Dependency Issue for Events Carousel - K
- [x] #1072 - Investigate new Jobs Listing Service + Talk to TDM - R, G
- [x] Circulate Web Dev Job Description - R, G, K, N
- [x] Lisa Guernsey standup old website - N
- [x] Fixed Program Post Home Page Datepicker Issue - K
- [x] Deployed Dynamic Subscriptions Update & Populated with Subscriptions List - K
- [x] Review website setup/design with Nat, Georgia, anyone else - K, G, N
