### ISSUE TITLE
Week of July 18th - ToDos

### ISSUE THREAD

**Issue by georgiamoon** [newamericafoundation/newamerica-cms#1090]
- [ ] #1037 - Build out Data Viz Project Structure - K
- [ ] #259 - Style Donate Embed - B, Jacqueline, R
- [ ] #1073 - Decide what New America HQ should be called/differentiate between DC and HQ - R
- [ ] Designs for Social media sharing - R, B
- [x] #1089 - Designs for In-Depth Projects Home Page - R
- [x] Review website setup/design with Nat, Georgia, anyone else - K, G, N
- [ ] Lisa Guernsey decide how to do content transfer - N, R, LG
- [ ] Look at remaining data transfer tasks - G, N, R, K
