### ISSUE TITLE
Week of July 25th - ToDos

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1094]
- [x] #1089 - Build out In-Depth Homepage - K
- [ ] Investigate Experts Analytics/ where in-depth should live on site - R
- [x] #1093 - Finish building out collapsible content block - K
- [ ] #1081 #1054 - Review Events Carousel and In-depth Project Page PRs - N, C 
- [ ] #259 - Style Donate Embed - B, Jacqueline, R
- [ ] #1073 - Decide what New America HQ should be called/differentiate between DC and HQ - R
- [ ] Designs for Social media sharing - R, B
- [x] Web Developer Job Outreach to Candidates - R
- [x] Decide job interview procedure/technical tasks - G, N, K, R
- [x] #1096 - Built Fixed Banner to promote survey - K
