### ISSUE TITLE
Week of August 15th - ToDos

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1115]
- [x] #1033 - Bio Photo Links - K
- [x] - Deploy In Depth Template Branch to a Staging Site for Testing - K
- [x] - #1084 - In Depth - Set project logo link field - K
- [x] - Authentication for Data Projects Backend- K
- [ ] - #1087 - Finish Read More Collapsible Content Block - K
- [x] - #1114 - Finish Designs for In-depth Footer Nav - R
- [ ] - Designs for Care Index - R, T, B
- [ ] - Designs for Homegrown - R, T, B
- [ ] - Finalize Name for In-depth - R
