### ISSUE TITLE
Week of September 12th - ToDos

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1145]
- [x] newamericafoundation/newamerica-data-projects#66, newamericafoundation/newamerica-data-projects#67, newamericafoundation/newamerica-data-projects#68 - In Depth Template Minor Styling Edits - K
- [x] Padding for In-depth nav dots - K
- [x] newamericafoundation/newamerica-data-projects#25 Additional Fact Boxes - K
- [x] Captcha for New America Subscribe Validation - K
- [x] newamericafoundation/newamerica-data-projects#69 - Separate Data Viz Webpack Build Scripts - K
- [x] newamericafoundation/newamerica-data-projects#73 - Homegrown Deadly Attacks Step Chart - K
- [ ] Table Styling Edits - K
- [x] newamericafoundation/newamerica-data-projects#7 US Map for Care Index - K
- [ ] #1093 - Finish Collapsible Content Block - K
- [x] SVG and PNG download functionality - K
- [x] newamericafoundation/newamerica-data-projects#11 Grouped Bar Chart for Care Index - K
- [ ] Additional Field for In-Depth Dataset Citation Text - K
- [x] Final Viz List/Designs for Care Index - R
- [x] Redirect for Security Data Extremists data - N
- [x] Edit SecurityData Site Drones page per email - G
