### ISSUE TITLE
Week of September 26 - ToDos

### ISSUE THREAD

**Issue by kjacks** [newamericafoundation/newamerica-cms#1155]
- [x] #1093 - Collapsible Content Block - K
- [x] newamericafoundation/newamerica-data-projects#7 - Finalize Dataviz Table - K
- [x] newamericafoundation/newamerica-data-projects#105 - Quantize Scale Domain Rounding - K
- [x] #1150 - Image Block Max Size - K
- [x] Resource Security Dataviz Planning - K, R
- [x] Documentation/Prep for Andrew - K, G, R, N
