### ISSUE TITLE
Week of October 3rd & 10th

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1176]
Kirk
- [x] Andrew onboarding
- [ ] Resource Security build
- [x] Preliminary meetings on FEBP and Drones
- [x] #1122 Draft pages bug

Andrew
- [x] Overview of technologies/stack
- [x] #442 Grey intro block
- [ ] #1078 Implementing RSS feeds
- [ ] #965 Subscribe popup for Weekly
- [ ] #1051 Removing the search button, and generating results when filter values change

Ross
- [ ] #1163 Feedback on the way we describe people in search
- [ ] Preliminary drones designs 
- [ ] Content promotion card designs

Georgia

Nat

Tyler
- [ ] Preliminary FEBP designs

Jeff
- [ ] Preliminary FEBP designs
