### ISSUE TITLE
Week of October 17th

### ISSUE THREAD

**Issue by LomaxRx** [newamericafoundation/newamerica-cms#1185]
**Ross** 

- [ ] Social buttons -- (in depth nav exception?)

**Kirk**  

- [ ]  Resource Security build
- [x] Print and download png for data viz elements
- [x] Social shares for data viz elements 
- [ ] Finishing profile pages for in-depth projects
- [x] #1172 Upgrade to Wagtail 1.6.3
- [x] #1163 remove "person" from bio page search results listings
- [x] #1191 Reduced post body default video aspect ratio
- [x] #1194 Weekly - Reduce Number of Articles in "Also in this Edition"

**Andrew**

- [ ] Test/Push grey into blocks and rss feed
- [ ] Testing dynamic front-end

**Nat** 

- [ ] #1184 Update Privacy Policy

**Georgia** 

- [ ] Update WOD-Military to use DriveShaft

**Web Stakeholder 10/20**

- [ ] Introduce stakeholders to @LomaxRx
- [ ] #442 - Grey intro block
- [ ] #1078 Implementing RSS feeds
- [ ] #1170 Design completed for fixed social media buttons and RSS feeds (feedback welcome)
- [ ] #1033 - Bio Photos now link to full resolution
- [ ] #965 Subscribe popup for Weekly
- [ ] #1051 Investigating client side / more dynamic approach to generating content on content grids and elsewhere.
- [ ] #1122 - Some have pointed out a few locations on the site where draft pages were showing; this is fixed.
- [ ] Tip: avoiding double spacing in blogs etc using `<BR><BR>`
- [ ] #1163 Removing the "people" description in search / content grids.
- [ ] In Depth section launched. (Explain purpose of In Depth; how it pulls data from Google Sheets.) Care Index and Homegrown Terrorism launched, and work ongoing on FEBP, Resource Security climatic events map, drones project rebuild, OTI timeline, and Asset Building financial opportunity map. If time, brief review of some of the features of existing projects, e.g. maps v charts v fact boxes, download PNG option, addition of profile pages for in-depth projects (may be of interest to education).
- [ ] #1184 privacy policy update.
- [ ] High priority items that are upcoming, but not being built yet: "Fresh Analysis" on homepage, moderator/permissions issue in Wagtail, full staff directory, content promotion cards, related content, tags, AWS cleanup, Wagtail update
- [ ] Future of web stakeholder meetings - once a month? Are they helpful? Would an email suffice?
- [ ] Feedback / questions
