### ISSUE TITLE
Week of October 31st

### ISSUE THREAD

**Issue by LomaxRx** [newamericafoundation/newamerica-cms#1204]
### Kirk
- [x] newamericafoundation/newamerica-data-projects#121 Resource Security build
- [ ] #1196 Finishing profile pages for in-depth projects
- [x] World of Drones design / proposal to Alyssa

### Andrew
- [ ] Deploy!
- [x] change RSS pubdate
- [ ] Annual Website work planning / starting
- [ ] [FeatureSet 11/2016 - 12/2016](https://github.com/newamericafoundation/newamerica-cms/milestone/4) Meeting with @rossvanderlinde ?

### Ross
- [ ] #1170 Social Media Icons designs

### Nat
- [ ] Weekly Wonk > New America Weekly transfer #898
