### ISSUE TITLE
Week of November 14-21

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1210]
Kirk
- [ ] #1196 Finalize profile pages for in-depth projects
- [x] Review/deploy pull requests
- [x] #1198 Link to individual panel anchors
- [x] add loading gif to dataviz blocks
- [ ] World of Drones finalize

Andrew
- [x] Conference template feedback
- [x] #1206 Google Analytics on PDFs
- [ ] Dynamic approach
- [ ] #1175 RSS page template implementation

Ross
- [ ] Navigation review for In-Depth with Kirk - next week
- [x] CSS feedback for Conference template http://na-preview.herokuapp.com/conference/annual-conference/ Line height to 95%, and nav bar button shading
- [ ] Design conversations for Our People and other grid-type templates w/ comms team et al - next week
- [x] Feedback on #1205 weekly sidebar breaking
- [x] Possible design #1181 for PDF download - next week
- [ ] Previews of #1175 RSS feed designs, based on conversation at web stakeholder
- [ ] Send out minutes from web stakeholder, incorporating RSS designs (based on conversation) and notes on what has subsequently been deployed (Tuesday)

Nat
- [ ] #898 Weekly content
- [ ] #1184 Privacy policy

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/113920320650537/212295645535284)
