### ISSUE TITLE
ToDo - July 24

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1324]
# Andrew
- [ ] Search widget/page
- [ ] Subscribe widgets
- [ ] Refining The Weekly in React (next week) + feedback from web team
- [ ] Topics tagging model/pages
- [ ] Location tagging model
- [ ] In Depth implementation - awaiting Ellie's feedback
- [ ] Send Weekly archive to Ross & Maria

# Kirk
- [ ] In Depth structure/design finalizing conversation - Andrew has drawn up agenda items, we need to set aside time to talk
- [ ] Yemen/Somalia (finalizing, forwarding from natsec, closing natsec)
- [ ] Cyber malware project
- [ ] Asset Allocator Index - awaiting data/answers
- [ ] FEBP (incl. final data issues, re-routing from current site
- [ ] Standing item: monthly email + think about structure + chatting with Laura

# Alex
- [ ] MTN
- [ ] Working with Andrew and Laura to set up CM segment-Salesforce campaigns/custom field, potentially end the need for once monthly manual updates of general program campaigns in SF.

# Ross
- [ ] Email stakeholders with way forward on Thursday meetings: open office hours, 1) new data projects, 2) bugs, 3) site requests, anything else. Every Thursday between 1 and 3pm. At the web team's desks on 9th floor. Less of a need for stakeholder conversations that involve everyone, whereas in future we'll focus on ad hoc stakeholder meetings for specific topics (e.g. programs will fellows component assembled to chat about how fellows are displayed/tagged on the website). Monthly email with updates, starting at the end of July. 
- [ ] Talk to Tyra re monthly email to all-staff
- [ ] Overarching CSS feedback - differentiate between direct/descriptive feedback
- [ ] Speak to TR: FEBP K-12 - future of the project / Rackspace $$$
- [ ] Intern updating Weekly archives
- [ ] Search widget feedback
- [ ] Topics design / updated Sketch file to Andrew

# Next Week (added by Ross)
- [ ] Privacy policy
- [ ] Review AWS and Rackspace cost situations
