### ISSUE TITLE
ToDo - September 18

### ISSUE THREAD

**Issue by rossvanderlinde** [newamericafoundation/newamerica-cms#1329]
# Andrew
- [ ] Build additional content type
- [ ] Subprogram landing page as simple page
- [x] In Depth templates

# Kirk
- [ ] In Depth structure/design finalizing
- [ ] BW2 Asset Allocator Index - awaiting data/answers
- [ ] CESNA youth apprenticeship meeting
- [ ] Anti-Muslim Restrictions Project
- [ ] Higher Ed Index (incl. final data issues, re-routing from current site)
- [ ] Standing item: monthly email

# Alex
- [ ] MTN
- [ ] CM segment-Salesforce campaigns/custom field, potentially end the need for once monthly manual updates of general program campaigns in SF.

# Ross
- [ ] Intern updating Weekly archives.
- [ ] Privacy policy - circulate current version, get final inputs, and then ask Tyra/Barry.

# Georgia
- [ ] Review privacy policy!
