### ISSUE TITLE
Working on week of June 6th - ToDos

### ISSUE THREAD

**Issue by georgiamoon** [newamericafoundation/newamerica-cms#964]
Aggregate Issue for the ToDos this week:

- [x] #837 - Implement Events Page Setup - K & S
- [x] #855 - Update Person Model to not display drafts - S
- [x] #963 - EdCentral Transfer - S
- [ ] #942 - Post Author Order - K & S
- [x] #862 - Push Refactor Expanded Header Branch - K
- [ ] #912 - Page Title for Promoting Content on Home Page - K & R
- [x] #169 - AWS Audit - S & G
- [x] #913 - Upgrade Wagtail - S
- [ ] #949 #448 - Integrating Table and Button Streamfield Blocks - K 
- [x] #968 - Improve Site-wide Print Styling - K
- [x] #523 - Unify SCSS and JS breakpoint declarations - K
- [x] #975 - Redirects for download folder 404 - S
- [x] #982 - Add Weekly Subscription Elements to Weekly Articles - K
- [x] #979 - Updating query to include location based programs in content grid dropdown menu
- [x] #987 - Refactor OTI Customization - K
- [x] #992 - Fix Programs Dropdown Height Overflow Bug - K

**Comment by georgiamoon** [comment]
Marking #169 done from a "this week" perspective, but there's more to do there on other weeks.
